#!/usr/bin/env python3
"""One causal Nav2 trial for learned-policy task impact under PIT."""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import statistics
import subprocess
import threading
import time

from geometry_msgs.msg import PoseWithCovarianceStamped, Twist, TwistStamped
from lifecycle_msgs.srv import GetState
from nav_msgs.msg import Path as NavPath
from nav2_simple_commander.robot_navigator import BasicNavigator, TaskResult
import rclpy
from rclpy.executors import SingleThreadedExecutor
from rclpy.node import Node
from rclpy.parameter import Parameter
import yaml

from nav2_trial import Nav2Gate, clone_twist, make_pose
from pit_core.core import file_sha256


REVISION = "learned-task-impact-trial-v11-post-filter-boundary"
START_X, START_Y = -2.0, -0.5
OBSTACLE_X, OBSTACLE_Y = -1.45, 0.15
ROBOT_PLUS_OBSTACLE_RADIUS_M = 0.47
TRIGGER_REGION = {
    "kind": "radial_distance_from_start",
    "start_x": START_X,
    "start_y": START_Y,
    "min_distance_m": 0.10,
}


def gz_service(service: str, request_type: str, request: str) -> bool:
    completed = subprocess.run(
        [
            "gz", "service", "-s", service,
            "--reqtype", request_type, "--reptype", "gz.msgs.Boolean",
            "--timeout", "5000", "--req", request,
        ],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, timeout=10.0, check=False,
    )
    return completed.returncode == 0 and "true" in completed.stdout.lower()


def wait_until_nav2_active(navigator: BasicNavigator, timeout_s: float = 30.0) -> None:
    """Bound Nav2/AMCL startup so infrastructure failures can be retried cleanly."""
    deadline = time.monotonic() + timeout_s

    def wait_active(node_name: str) -> None:
        client = navigator.create_client(GetState, f"{node_name}/get_state")
        while time.monotonic() < deadline:
            if not client.wait_for_service(timeout_sec=0.5):
                continue
            future = client.call_async(GetState.Request())
            rclpy.spin_until_future_complete(navigator, future, timeout_sec=1.0)
            if future.done() and future.result() is not None:
                if future.result().current_state.label == "active":
                    return
            time.sleep(0.2)
        raise TimeoutError(f"{node_name} did not become active within {timeout_s:.1f} s")

    wait_active("amcl")
    while not navigator.initial_pose_received and time.monotonic() < deadline:
        navigator._setInitialPose()
        rclpy.spin_once(navigator, timeout_sec=0.5)
    if not navigator.initial_pose_received:
        raise TimeoutError(f"AMCL initial pose was not received within {timeout_s:.1f} s")
    wait_active("bt_navigator")


def spawn_obstacle() -> bool:
    sdf = (
        '<sdf version="1.9"><model name="pit_task_obstacle"><static>true</static>'
        '<link name="link"><collision name="collision"><geometry><cylinder><radius>0.25</radius>'
        '<length>0.8</length></cylinder></geometry></collision><visual name="visual"><geometry>'
        '<cylinder><radius>0.25</radius><length>0.8</length></cylinder></geometry>'
        '<material><ambient>1 0 0 1</ambient><diffuse>1 0 0 1</diffuse></material>'
        '</visual></link></model></sdf>'
    )
    escaped = sdf.replace('"', '\\"')
    request = (
        f'sdf: "{escaped}", name: "pit_task_obstacle", allow_renaming: false, '
        'pose: {position: {x: 0, y: 5, z: 0.4}, orientation: {w: 1}}'
    )
    return gz_service("/world/default/create", "gz.msgs.EntityFactory", request)


def set_obstacle_pose(x: float, y: float) -> bool:
    request = (
        'name: "pit_task_obstacle", '
        f'position: {{x: {x}, y: {y}, z: 0.4}}, '
        'orientation: {w: 1}'
    )
    return gz_service("/world/default/set_pose", "gz.msgs.Pose", request)


def deactivate_obstacle() -> bool:
    return set_obstacle_pose(0.0, 5.0)


def predicted_endpoint(
    x: float, y: float, yaw: float, linear_x: float, angular_z: float, path_m: float
) -> tuple[float, float]:
    """Place the obstacle on the arc generated by the queued forward command."""
    travel_s = path_m / max(1e-6, linear_x)
    if abs(angular_z) <= 1e-6:
        return x + path_m * math.cos(yaw), y + path_m * math.sin(yaw)
    radius = linear_x / angular_z
    end_yaw = yaw + angular_z * travel_s
    return (
        x + radius * (math.sin(end_yaw) - math.sin(yaw)),
        y - radius * (math.cos(end_yaw) - math.cos(yaw)),
    )


class LearnedGate(Nav2Gate):
    def __init__(self, mode: str, scenario: str, source: str, raw: dict) -> None:
        super().__init__(mode, scenario, source, raw)
        self.analysis_anchor_monotonic: float | None = None
        self.analysis_anchor_wall_ns: int | None = None
        self.trigger_pose: dict | None = None
        self.latest_pose: dict | None = None
        self.spatial_trigger_ready = False
        self.obstacle_x: float | None = None
        self.obstacle_y: float | None = None
        self.task_active = False
        self.external_fault_arm = False
        self.post_filter_mode = bool(self.experiment.get("post_filter_candidate_topic"))
        self.controller_stage = None
        if self.post_filter_mode:
            self.controller_stage = self.create_publisher(
                Twist, self.experiment["controller_stage_output_topic"], 10
            )
            self.create_subscription(
                Twist,
                self.experiment["post_filter_candidate_topic"],
                self.on_post_filter_candidate,
                10,
            )
        self.create_subscription(PoseWithCovarianceStamped, "/amcl_pose", self.on_pose, 10)

    def process_candidate(self, candidate: TwistStamped, is_fallback: bool) -> None:
        if not self.post_filter_mode:
            super().process_candidate(candidate, is_fallback)
            return
        # Preserve Nav2's Collision Monitor as an independent first-stage
        # mechanism. PIT is evaluated only at the downstream ROS 2 boundary.
        self.controller_stage.publish(clone_twist(candidate.twist))

    def on_post_filter_candidate(self, message: Twist) -> None:
        candidate = TwistStamped()
        wall_ns = time.time_ns()
        candidate.header.stamp.sec = wall_ns // 1_000_000_000
        candidate.header.stamp.nanosec = wall_ns % 1_000_000_000
        candidate.twist = clone_twist(message)
        if (
            self.scenario == "safe_but_late"
            and self.external_fault_arm
            and self.fault_started is None
            and bool(self.fault.get("freeze_first_command", False))
        ):
            self.frozen_fault_command = clone_twist(message)
            if self.trigger_pose is not None:
                self.trigger_pose["boundary_queued_command"] = {
                    "linear_x": float(message.linear.x),
                    "angular_z": float(message.angular.z),
                }
        Nav2Gate.process_candidate(
            self, candidate, is_fallback=bool(self.core.transferred)
        )

    def on_pose(self, message: PoseWithCovarianceStamped) -> None:
        if not self.task_active:
            return
        x = float(message.pose.pose.position.x)
        y = float(message.pose.pose.position.y)
        orientation = message.pose.pose.orientation
        yaw = math.atan2(
            2.0 * (orientation.w * orientation.z + orientation.x * orientation.y),
            1.0 - 2.0 * (orientation.y * orientation.y + orientation.z * orientation.z),
        )
        self.latest_pose = {"x": x, "y": y, "yaw": yaw}
        if self.external_fault_arm:
            return
        inside = math.hypot(x - START_X, y - START_Y) >= TRIGGER_REGION["min_distance_m"]
        if not inside:
            return
        if float(self.fault.get("predictive_obstacle_path_m", 0.0)) > 0.0:
            self.spatial_trigger_ready = True
            return
        self.arm_fault(x, y, yaw)

    def arm_fault(
        self, x: float, y: float, yaw: float, command: TwistStamped | None = None
    ) -> None:
        self.external_fault_arm = True
        self.analysis_anchor_monotonic = time.monotonic()
        self.analysis_anchor_wall_ns = time.time_ns()
        self.trigger_pose = {"x": x, "y": y, "yaw": yaw}
        if command is None:
            return
        self.frozen_fault_command = clone_twist(command.twist)
        linear_x = float(command.twist.linear.x)
        angular_z = float(command.twist.angular.z)
        self.trigger_pose["queued_command"] = {
            "linear_x": linear_x,
            "angular_z": angular_z,
        }
        self.obstacle_x, self.obstacle_y = predicted_endpoint(
            x, y, yaw, linear_x, angular_z,
            float(self.fault["predictive_obstacle_path_m"]),
        )
        self.trigger_pose["predicted_obstacle_xy"] = [self.obstacle_x, self.obstacle_y]

    def on_learned_candidate(self, message: TwistStamped) -> None:
        self.metrics["learned_candidates"] += 1
        if not self.task_active:
            return
        if (
            not self.external_fault_arm
            and self.spatial_trigger_ready
            and float(self.fault.get("predictive_obstacle_path_m", 0.0)) > 0.0
            and self.latest_pose is not None
            and float(message.twist.linear.x)
            >= float(self.fault.get("queued_command_min_linear_x", 0.20))
            and abs(float(message.twist.angular.z))
            <= float(self.fault.get("queued_command_max_abs_angular_z", 0.35))
        ):
            self.arm_fault(
                self.latest_pose["x"], self.latest_pose["y"], self.latest_pose["yaw"], message
            )
        if (
            not self.external_fault_arm
            and bool(self.fault.get("freeze_first_command", False))
            and float(self.fault.get("predictive_obstacle_path_m", 0.0)) <= 0.0
        ):
            self.frozen_fault_command = clone_twist(message.twist)
        if self.core.transferred:
            self.metrics["learned_candidates_ignored_after_transfer"] += 1
            return
        self.metrics["selected_primary_candidates"] += 1
        self.process_candidate(message, is_fallback=False)


class ClearanceMonitor(Node):
    def __init__(self) -> None:
        super().__init__("pit_task_clearance_monitor")
        self.active = False
        self.obstacle_x: float | None = None
        self.obstacle_y: float | None = None
        self.min_center_distance_m: float | None = None
        self.trace: list[dict] = []
        self.create_subscription(PoseWithCovarianceStamped, "/amcl_pose", self.on_pose, 10)

    def activate_at(self, x: float, y: float, obstacle_x: float, obstacle_y: float) -> None:
        self.active = True
        self.obstacle_x = obstacle_x
        self.obstacle_y = obstacle_y
        self.record(x, y)

    def deactivate(self) -> None:
        self.active = False

    def record(self, x: float, y: float) -> None:
        if self.obstacle_x is None or self.obstacle_y is None:
            return
        dx = x - self.obstacle_x
        dy = y - self.obstacle_y
        distance = math.hypot(dx, dy)
        self.min_center_distance_m = distance if self.min_center_distance_m is None else min(self.min_center_distance_m, distance)
        self.trace.append({"wall_time_ns": time.time_ns(), "center_distance_m": distance})

    def on_pose(self, message: PoseWithCovarianceStamped) -> None:
        if not self.active:
            return
        self.record(
            float(message.pose.pose.position.x),
            float(message.pose.pose.position.y),
        )


def point_to_segment_distance(
    x: float, y: float, first: tuple[float, float], second: tuple[float, float]
) -> float:
    ax, ay = first
    bx, by = second
    dx, dy = bx - ax, by - ay
    denominator = dx * dx + dy * dy
    if denominator <= 1e-12:
        return math.hypot(x - ax, y - ay)
    fraction = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / denominator))
    return math.hypot(x - (ax + fraction * dx), y - (ay + fraction * dy))


class GlobalPlanMonitor(Node):
    def __init__(self) -> None:
        super().__init__("pit_task_global_plan_monitor")
        self.points: list[tuple[float, float]] = []
        self.trace: list[dict] = []
        self.create_subscription(NavPath, "/plan", self.on_plan, 10)

    def on_plan(self, message: NavPath) -> None:
        self.points = [
            (float(pose.pose.position.x), float(pose.pose.position.y))
            for pose in message.poses
        ]
        self.trace.append(
            {
                "wall_time_ns": time.time_ns(),
                "frame_id": message.header.frame_id,
                "points": [[x, y] for x, y in self.points],
            }
        )

    def cross_track_error(self, x: float | None, y: float | None) -> float | None:
        if x is None or y is None or not self.points:
            return None
        if len(self.points) == 1:
            return math.hypot(x - self.points[0][0], y - self.points[0][1])
        return min(
            point_to_segment_distance(x, y, first, second)
            for first, second in zip(self.points, self.points[1:])
        )


def interpolate_anchor(trace: list[dict], anchor: float) -> tuple[float | None, float]:
    finite = [row for row in trace if math.isfinite(row["distance_remaining_m"])]
    if not finite:
        return None, 0.0
    anchor_row = min(finite, key=lambda row: abs(row["monotonic_s"] - anchor))
    before = [row for row in finite if anchor - 1.0 <= row["monotonic_s"] < anchor_row["monotonic_s"]]
    if before:
        first = before[0]
        dt = max(1e-6, anchor_row["monotonic_s"] - first["monotonic_s"])
        pre_rate = max(0.0, (first["distance_remaining_m"] - anchor_row["distance_remaining_m"]) / dt)
    else:
        pre_rate = 0.0
    return float(anchor_row["distance_remaining_m"]), pre_rate


def progress_loss_auc(trace: list[dict], anchor: float | None) -> float | None:
    if anchor is None:
        return None
    anchor_distance, pre_rate = interpolate_anchor(trace, anchor)
    if anchor_distance is None:
        return None
    samples = []
    for row in trace:
        t = row["monotonic_s"] - anchor
        distance = row["distance_remaining_m"]
        if 0.0 <= t <= 5.0 and math.isfinite(distance):
            actual_progress = anchor_distance - distance
            expected_progress = pre_rate * t
            samples.append((t, max(0.0, expected_progress - actual_progress)))
    if len(samples) < 2:
        return None
    area = 0.0
    for (t0, y0), (t1, y1) in zip(samples, samples[1:]):
        area += 0.5 * (y0 + y1) * (t1 - t0)
    return area


def post_trigger_auc_max(
    trace: list[dict], anchor: float | None, field: str
) -> tuple[float | None, float | None]:
    if anchor is None:
        return None, None
    samples = []
    for row in trace:
        value = row.get(field)
        relative_t = row.get("monotonic_s", 0.0) - anchor
        if (
            isinstance(value, (int, float))
            and math.isfinite(value)
            and 0.0 <= relative_t <= 5.0
        ):
            samples.append((relative_t, float(value)))
    if len(samples) < 2:
        return None, None
    area = sum(
        0.5 * (first[1] + second[1]) * (second[0] - first[0])
        for first, second in zip(samples, samples[1:])
    )
    return area, max(value for _, value in samples)


def path_length(trace: list[dict]) -> float:
    points = [(row["x"], row["y"]) for row in trace if row["x"] is not None and row["y"] is not None]
    return sum(math.hypot(bx - ax, by - ay) for (ax, ay), (bx, by) in zip(points, points[1:]))


def geometric_overlap_metrics(trace: list[dict]) -> tuple[int, float]:
    """Count footprint/obstacle overlap episodes and their observed duration."""
    episodes = 0
    duration_s = 0.0
    previous: dict | None = None
    previous_inside = False
    for row in sorted(trace, key=lambda item: item["wall_time_ns"]):
        inside = float(row["center_distance_m"]) < ROBOT_PLUS_OBSTACLE_RADIUS_M
        if inside and not previous_inside:
            episodes += 1
        if previous is not None and previous_inside:
            duration_s += max(0.0, (row["wall_time_ns"] - previous["wall_time_ns"]) / 1e9)
        previous = row
        previous_inside = inside
    return episodes, duration_s


def recovery_time(trace: list[dict], anchor: float | None) -> float | None:
    if anchor is None:
        return None
    anchor_distance, _ = interpolate_anchor(trace, anchor)
    if anchor_distance is None:
        return None
    for row in trace:
        if row["monotonic_s"] >= anchor and row["distance_remaining_m"] <= anchor_distance - 0.05:
            return row["monotonic_s"] - anchor
    return None


def jerk_rms(final_trace: list[dict]) -> float | None:
    accelerations = []
    for first, second in zip(final_trace, final_trace[1:]):
        dt = (second["wall_time_ns"] - first["wall_time_ns"]) / 1e9
        if 0.005 <= dt <= 0.5:
            accelerations.append((second["wall_time_ns"], (second["linear_x"] - first["linear_x"]) / dt))
    jerks = []
    for first, second in zip(accelerations, accelerations[1:]):
        dt = (second[0] - first[0]) / 1e9
        if 0.005 <= dt <= 0.5:
            jerks.append((second[1] - first[1]) / dt)
    return math.sqrt(statistics.mean(value * value for value in jerks)) if jerks else None


def main() -> int:
    global OBSTACLE_X, OBSTACLE_Y
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("independent", "pit"), required=True)
    parser.add_argument("--condition", choices=("normal", "burst_late"), required=True)
    parser.add_argument("--scene", choices=("static", "crossing"), required=True)
    parser.add_argument(
        "--policy",
        choices=("reactive_scan_goal_bc", "temporal_scan_goal_bc", "drl", "drl_vo"),
        required=True,
    )
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--model-weights", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--goal-x", type=float, default=2.0)
    parser.add_argument("--goal-y", type=float, default=0.5)
    parser.add_argument("--obstacle-x", type=float, default=OBSTACLE_X)
    parser.add_argument("--obstacle-y", type=float, default=OBSTACLE_Y)
    parser.add_argument("--post-trigger-horizon-s", type=float, default=0.0)
    parser.add_argument("--timeout", type=float, default=75.0)
    parser.add_argument("--wall-watchdog", type=float, default=180.0)
    args = parser.parse_args()
    OBSTACLE_X, OBSTACLE_Y = args.obstacle_x, args.obstacle_y
    raw = yaml.safe_load(args.profile.read_text(encoding="utf-8"))
    scenario = "normal" if args.condition == "normal" else "safe_but_late"
    rclpy.init()
    gate = LearnedGate(args.mode, scenario, args.policy, raw)
    monitor = ClearanceMonitor()
    plan_monitor = GlobalPlanMonitor()
    executor = SingleThreadedExecutor()
    executor.add_node(gate); executor.add_node(monitor); executor.add_node(plan_monitor)
    thread = threading.Thread(target=executor.spin, daemon=True)
    thread.start()
    navigator = BasicNavigator(node_name=f"task_impact_{args.policy}_{args.mode}_{args.seed}")
    navigator.set_parameters([Parameter("use_sim_time", value=True)])
    goal_result, sim_time_s = "NOT_STARTED", None
    feedback_trace: list[dict] = []
    obstacle_spawned = args.scene == "static" or spawn_obstacle()
    obstacle_activated = False
    obstacle_deactivated = False
    obstacle_activated_at: float | None = None
    started = time.monotonic()
    try:
        navigator.setInitialPose(make_pose(navigator, START_X, START_Y, latest=True))
        wait_until_nav2_active(navigator)
        gate.select_controller(raw["experiment"]["primary_controller"])
        time.sleep(0.5)
        gate.task_active = True
        navigator.goToPose(make_pose(navigator, args.goal_x, args.goal_y))
        started = time.monotonic()
        while not navigator.isTaskComplete():
            feedback = navigator.getFeedback()
            if feedback is not None:
                sim_time_s = feedback.navigation_time.sec + feedback.navigation_time.nanosec / 1e9
                pose = getattr(feedback, "current_pose", None)
                x = None if pose is None else float(pose.pose.position.x)
                y = None if pose is None else float(pose.pose.position.y)
                feedback_trace.append(
                    {
                        "wall_time_ns": time.time_ns(),
                        "monotonic_s": time.monotonic(),
                        "navigation_sim_time_s": sim_time_s,
                        "distance_remaining_m": float(getattr(feedback, "distance_remaining", float("nan"))),
                        "number_of_recoveries": int(getattr(feedback, "number_of_recoveries", 0)),
                        "x": x,
                        "y": y,
                        "cross_track_error_m": plan_monitor.cross_track_error(x, y),
                    }
                )
            if args.scene == "crossing" and not obstacle_activated and gate.analysis_anchor_monotonic is not None:
                if gate.obstacle_x is not None and gate.obstacle_y is not None:
                    OBSTACLE_X, OBSTACLE_Y = gate.obstacle_x, gate.obstacle_y
                obstacle_activated = set_obstacle_pose(OBSTACLE_X, OBSTACLE_Y)
                if obstacle_activated and gate.trigger_pose is not None:
                    obstacle_activated_at = time.monotonic()
                    monitor.activate_at(
                        gate.trigger_pose["x"], gate.trigger_pose["y"],
                        OBSTACLE_X, OBSTACLE_Y,
                    )
            active_duration_s = float(raw["fault"].get("obstacle_active_duration_s", 0.0))
            if (
                obstacle_activated and not obstacle_deactivated
                and obstacle_activated_at is not None and active_duration_s > 0.0
                and time.monotonic() - obstacle_activated_at >= active_duration_s
            ):
                obstacle_deactivated = deactivate_obstacle()
                if obstacle_deactivated:
                    monitor.deactivate()
            if sim_time_s is not None and sim_time_s > args.timeout:
                navigator.cancelTask(); goal_result = "TIMEOUT_SIM"; break
            if (
                args.post_trigger_horizon_s > 0.0
                and gate.analysis_anchor_monotonic is not None
                and time.monotonic() - gate.analysis_anchor_monotonic
                >= args.post_trigger_horizon_s
            ):
                navigator.cancelTask(); goal_result = "HORIZON_COMPLETE"; break
            if time.monotonic() - started > args.wall_watchdog:
                navigator.cancelTask(); goal_result = "TIMEOUT_WALL"; break
            time.sleep(0.05)
        if goal_result == "NOT_STARTED":
            result = navigator.getResult()
            goal_result = {
                TaskResult.SUCCEEDED: "SUCCEEDED",
                TaskResult.CANCELED: "CANCELED",
                TaskResult.FAILED: "FAILED",
            }.get(result, f"UNKNOWN_{result}")
    finally:
        report = gate.report()
        anchor = gate.analysis_anchor_monotonic
        restricted_time = (
            float(sim_time_s)
            if goal_result in {"SUCCEEDED", "HORIZON_COMPLETE"} and sim_time_s is not None
            else args.timeout
        )
        overlap_episodes, overlap_duration_s = geometric_overlap_metrics(monitor.trace)
        cross_track_auc, cross_track_max = post_trigger_auc_max(
            feedback_trace, anchor, "cross_track_error_m"
        )
        report.update(
            {
                "revision": REVISION,
                "policy": args.policy,
                "mode": args.mode,
                "condition": args.condition,
                "scene": args.scene,
                "seed": args.seed,
                "rmw_implementation": os.environ.get("RMW_IMPLEMENTATION"),
                "goal": [args.goal_x, args.goal_y],
                "goal_result": goal_result,
                "post_trigger_horizon_s": args.post_trigger_horizon_s,
                "navigation_sim_time_s": sim_time_s,
                "restricted_navigation_time_s": min(args.timeout, restricted_time),
                "navigation_wall_time_s": time.monotonic() - started,
                "analysis_anchor_monotonic_s": anchor,
                "analysis_anchor_wall_ns": gate.analysis_anchor_wall_ns,
                "trigger_region": TRIGGER_REGION,
                "trigger_pose": gate.trigger_pose,
                "progress_loss_auc_5s": progress_loss_auc(feedback_trace, anchor),
                "cross_track_error_auc_5s_m_s": cross_track_auc,
                "cross_track_error_max_5s_m": cross_track_max,
                "recovery_time_s": recovery_time(feedback_trace, anchor),
                "path_length_m": path_length(feedback_trace),
                "linear_jerk_rms": jerk_rms(report["final_command_trace"]),
                "obstacle_spawned": obstacle_spawned,
                "obstacle_activated": obstacle_activated,
                "obstacle_deactivated": obstacle_deactivated,
                "obstacle_active_duration_s": float(raw["fault"].get("obstacle_active_duration_s", 0.0)),
                "obstacle_x": OBSTACLE_X,
                "obstacle_y": OBSTACLE_Y,
                "min_center_distance_m": monitor.min_center_distance_m,
                "min_geometric_clearance_m": (
                    None if monitor.min_center_distance_m is None
                    else monitor.min_center_distance_m - ROBOT_PLUS_OBSTACLE_RADIUS_M
                ),
                "geometric_overlap_observed": overlap_episodes > 0,
                "geometric_overlap_episode_count": overlap_episodes,
                "geometric_overlap_duration_s": overlap_duration_s,
                "clearance_trace": monitor.trace,
                "global_plan_trace": plan_monitor.trace,
                "navigation_feedback_trace": feedback_trace,
                "model_weight_sha256": file_sha256(args.model_weights),
                "profile_sha256": file_sha256(args.profile),
                "adapter_sha256": file_sha256(__file__),
                "gate_dependency_sha256": file_sha256(Path(__file__).with_name("nav2_trial.py")),
                "application_source_modified_loc": 0,
                "controller_source_modified_loc": 0,
                "active_primary_source": args.policy,
                "nav2_shadow_fallback_controller": raw["experiment"]["fallback_controller"],
                "middleware_enforcement_boundary": (
                    "post_collision_monitor_pre_actuator"
                    if gate.post_filter_mode else "pre_collision_monitor"
                ),
                "collision_monitor_preserved": gate.post_filter_mode,
                "post_filter_candidate_topic": raw["experiment"].get("post_filter_candidate_topic"),
                "prohibited_mppi_command_admissions": sum(
                    event.get("source") == "controller"
                    for event in report["raw_events"]
                    if not event.get("is_fallback", False)
                ),
            }
        )
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(report, indent=2))
        navigator.destroy_node(); executor.shutdown()
        gate.destroy_node(); monitor.destroy_node(); plan_monitor.destroy_node(); rclpy.shutdown()
        thread.join(timeout=2.0)
    return 0 if goal_result != "NOT_STARTED" else 2


if __name__ == "__main__":
    raise SystemExit(main())
